Checkpoint

diff --git a/bin/sb b/bin/sb
--- a/bin/sb
+++ b/bin/sb
@@ -30,9 +30,11 @@ parser_definition() {
 	disp    :usage  -h --help
 	disp    SCRIPT_VERSION    --version
 
-	msg         -- '' 'Commands:'
-	cmd new --  "Creates a new sandbox.           'sb new --help' for help"
-	#cmd sync -- "Refreshes sandbox configuration  'sb sync --help' for help"
+	msg           -- '' 'Commands:'
+	cmd new       -- "Creates a new sandbox.               'sb new   --help' for help"
+	cmd start     -- "Starts a sandbox                     'sb start --help' for help"
+	cmd stop      -- "Refreshes sandbox configuration      'sb stop  --help' for help"
+  cmd shell     -- "Starts a terminal shell in a sandbox 'sb shell  --help' for help"
 }
 
 parser_definition_new() {
@@ -40,6 +42,15 @@ parser_definition_new() {
 	msg -- '' 'Creates a new sandox within an existing project'
 	msg -- 'Options:'
   param   template      -t    --template-id                     validate:'template_regex "^[a-zA-Z](-|_|[a-zA-z]|[0-9]$)*"'    -- "The ID of the template to use for the sandbox. Defaults to \$SB_USER_DEFAULT_TEMPLATE_ID in sb-user.env if specified. Otherwise, defaults to \$SB_SYSTEM_DEFAULT_TEMPLATE_ID in sb-system.env"
+	param   sandbox       -s    --sandbox-id      init:="default" validate:'sandbox_regex "^[a-zA-Z](-|_|[a-zA-z]|[0-9]$)*"'     -- "The sandbox ID. A meaningful but short identifier for the sandbox. Defaults to 'default'."
+	param   project_path  -p    --project-path                                                                                   -- "The path to the project directory (the ".sb" directory). If not specified, $SCRIPT_NAME will attempt to find the path based on the current directory"
+	disp    :usage        -h    --help
+}
+
+parser_definition_shell() {
+	setup   REST error:error_init help:usage abbr:true -- "Usage: $SCRIPT_NAME init [<options>]"
+	msg -- '' 'Start'
+	msg -- 'Options:'
 	param   sandbox       -s    --sandbox-id      init:="default" validate:'sandbox_regex "^[a-zA-Z](-|_|[a-zA-z]|[0-9]$)*"'     -- "The sandbox ID. A meaningful but short identifier for the sandbox. Defaults to 'default'."
 	param   project_path  -p    --project-path                                                                                   -- "The path to the project directory (the ".sb" directory). If not specified, $SCRIPT_NAME will attempt to find the path based on the current directory"
 	disp    :usage        -h    --help
@@ -78,6 +89,139 @@ dir_search_tree_up_by_dirname() {
 			(cd .. && dir_search_tree_up_by_dirname "$1")
 		fi 
 	fi
+}
+
+
+shell() {
+
+  #read system defaults
+	sb_install_root=$SCRIPT_DIR/..
+	sb_env_root=$sb_install_root/env
+	sb_system_env_path=$sb_env_root/sb-system.env
+
+	SB_SYSTEM_DEFAULT_SANDBOX_ID=
+	if [ -f $sb_system_env_path ]; then
+		source $sb_system_env_path
+	fi
+
+  #Read the user's global defaults (if present)
+  SB_USER_ENV_PATH=
+  if [[ -v XDG_CONFIG_HOME && -f "$XDG_CONFIG_HOME/sb-user.env" ]]; then
+    SB_USER_ENV_PATH="$XDG_CONFIG_HOME/sb-user.env"
+  elif [ -f "$HOME/.config/sb/sb-user.env" ]; then
+    SB_USER_ENV_PATH="$HOME/.config/sb/sb-user.env"
+  elif [ -f "$HOME/.sb/sb-user.env" ]; then
+    SB_USER_ENV_PATH="$$HOME/.sb/sb-user.env"
+  fi
+
+  SB_USER_DEFAULT_SANDBOX_ID=
+  if [ -n "$SB_USER_ENV_PATH" ]; then
+    source "$SB_USER_ENV_PATH"
+  fi
+
+  # Read the project env
+	if [ -z "$project_path" ]; then
+		#search for project root
+		project_path=$(dir_search_tree_up_by_dirname ".sb") 
+		if [ -z "$project_path" ]; then
+			echo  "$SCRIPT_NAME: Error: Unable to find sandbox project root directory. 'cd' into the directory tree containing the sandbox project or run 'sb-project init' to create a project"
+			exit 1
+		fi
+	else
+		if [ ! -d "$project_path" ]; then
+			echo "$SCRIPT_NAME: Error: Unable to start shell session- sandbox project root directory '$project_path' does not exist"
+			exit 1
+		fi
+	fi
+
+	project_path_abs=$(readlink -f $project_path)
+	project_env_path=$project_path/sb-project.env
+	if [ ! -f "$project_env_path" ]; then
+		echo "$SCRIPT_NAME: Error: Unable to start shell session- project configuration file '$project_path_abs' does not exist"
+		exit 1
+	fi
+
+  SB_PROJECT_DEFAULT_SANDBOX_ID=
+  SB_PROJECT_ID=
+	source $project_env_path
+
+  #get the sandbox ID
+	default_sandbox_source=
+	if [ -z "$sandbox" ]; then
+		sandbox=${SB_PROJECT_DEFAULT_SANDBOX_ID:-${SB_USER_DEFAULT_SANDBOX_ID:-$SB_SYSTEM_DEFAULT_SANDBOX_ID}}
+		default_sandbox_source=${SB_PROJECT_DEFAULT_SANDBOX_ID:+" project-default"}
+		[ -z "$default_sandbox_source" ] && template_source=${SB_USER_DEFAULT_SANDBOX_ID:+" user-default"}
+		[ -z "$default_sandbox_source" ] && template_source=${SB_SYSTEM_DEFAULT_SANDBOX_ID:+" system-default"}
+		if [ -z "$sandbox" ]; then
+			echo "$SCRIPT_NAME: Error: Unable to determine target sandbox- sandbox ID is specified on the command-lione and no project/user/system default sandvox ID is configured"
+			exit 1
+		fi
+  fi
+
+	sandbox_path=$project_path_abs/sandboxes/$sandbox
+	if [ ! -d "$sandbox_path" ]; then
+		echo "$SCRIPT_NAME: Error:Unable to start shell session- sandbox directory '$sandbox_path' does not exist"
+		exit 1
+	fi
+
+  sandbox_compose_env_path=$sandbox_path/sb-compose.env
+	if [ ! -f "$sandbox_compose_env_path" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- file '$sandbox_compose_env_path' does not exist"
+		exit 1
+	fi
+
+	SB_COMPOSE_SERVICE=
+  SB_SANDBOX_ROOT=$sandbox_path
+  SB_SANDBOX_ID=$sandbox
+	source $sandbox_compose_env_path
+
+	if [ -z "$SB_COMPOSE_SERVICE" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- variable 'SB_COMPOSE_SERVICE' is not defined in '$sandbox_compose_env_path'"
+		exit 1
+	fi
+
+  sandbox_env_path=$sandbox_path/sb-sandbox.env
+	if [ ! -f "$sandbox_env_path" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- file '$sandbox_env_path' does not exist"
+		exit 1
+	fi
+
+	SB_SHELL=
+	source $sandbox_env_path
+
+  if [ -z "$SB_SHELL" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- variable 'SB_SHELL' is not defined in '$sandbox_env_path'"
+		exit 1
+	fi
+
+  docker_compose_file_path=$sandbox_path/docker-compose.yml
+  if [ ! -f $docker_compose_file_path ]; then
+    echo "$SCRIPT_NAME: Sandbox validation error- file '$docker_compose_file_path' does not exist"
+    exit 1
+  fi
+
+  #Start service it is not running
+  service_id=$(docker compose -f $docker_compose_file_path ps --status=running $SB_COMPOSE_SERVICE -q)
+  if [ -z "$service_id" ]; then
+    echo "$SCRIPT_NAME: Starting sandbox '$sandbox'${default_sandbox_source}"
+    echo ""
+    echo "docker compose -f $docker_compose_file_path up -d"
+    docker compose -f $docker_compose_file_path up -d
+    if [ $? -ne 0 ]; then
+      echo "$SCRIPT_NAME: Failed to start sandbox"
+      exit 1
+    fi
+    echo ""
+  fi
+
+  echo "$SCRIPT_NAME: Starting shell session in sandbox '$sandbox'${default_sandbox_source}"
+  echo "$SCRIPT_NAME: docker compose -f $docker_compose_file_path exec $SB_COMPOSE_SERVICE $SB_SHELL"
+  docker compose -f $docker_compose_file_path exec $SB_COMPOSE_SERVICE $SB_SHELL
+  if [ $? -ne 0 ]; then
+    echo "$SCRIPT_NAME: Failed to start shell session"
+    exit 1
+  fi
+
 }
 
 new_sandbox() {
@@ -129,7 +273,7 @@ new_sandbox() {
 		echo "$SCRIPT_NAME: Error: Unable to create new sandbox- project configuration file '$project_path_abs' does not exist"
 		exit 1
 	fi
-	
+
 
 	SB_PROJECT_DEFAULT_TEMPLATE_ID=
 	source $project_env_path
@@ -324,15 +468,59 @@ new_sandbox() {
 		exit 
 	fi
 
-	echo ""
-	echo "$SCRIPT_NAME: Sandbox creation complete- create sandbox '$sandbox' at '$sandbox_dest_path'"
-	echo ""
-	echo "Next Steps:"
-	echo ""
-	echo "    - Start  : Run 'sb start' or 'cd $sandbox_dest_path && docker compose up -d'"
-	echo ""
-	echo "    - Attach : Run 'sb attach' or 'cd $sandbox_dest_path && docker compose exec sandbox /bin/bash"
-	echo ""
+	sandbox_env_path=$sandbox_dest_path/sb-sandbox.env
+	if [-f "$sandbox_env_path" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- file '$sandbox_env_path' does not exist"
+		exit 1
+	fi
+
+	SB_SHELL=
+	source $sandbox_env_path
+
+	if [-z "$SB_SHELL" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- variable 'SB_SHELL' is not defined in '$sandbox_env_path'"
+		exit 1
+	fi
+
+	sandbox_compose_env_path=$sandbox_dest_path/sb-compose.env
+	if [-f "$sandbox_compose_env_path" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- file '$sandbox_compose_env_path' does not exist"
+		exit 1
+	fi
+
+	SB_COMPOSE_SERVICE=
+	source $sandbox_compose_env_path
+
+	if [-z "$SB_COMPOSE_SERVICE" ]; then
+		echo "$SCRIPT_NAME: Sandbox validation error- variable 'SB_COMPOSE_SERVICE' is not defined in '$sandbox_compose_env_path'"
+		exit 1
+	fi
+
+	cat <<EOF
+
+Sandbox creation complete."
+
+Created sandbox '$sandbox' at '$sandbox_dest_path'
+
+Next Steps:
+
+  - Start the sandbox. Run:
+
+    'sb start' 
+	
+    or:
+	
+    'cd $sandbox_dest_path && docker compose up -d'
+	
+  - Start a shell session. Run:
+
+    'sb shell -s $sandbox'
+	
+    or:
+	
+    'cd $sandbox_dest_path && docker compose exec ${SB_COMPOSE_SERVICE} ${SB_SHELL}'
+
+EOF
 
 }
 
@@ -348,8 +536,15 @@ if [ $# -gt 0 ]; then
 				eval "$cmd_parser"
 				new_sandbox
 				;;
+		shell)
+				cmd_parser="$(getoptions parser_definition_shell)"
+				eval "$cmd_parser"
+				shell
+				;;        
 
-		--) # no subcommand, arguments only
+		--) 
+        usage
+        ;;
 	esac
 else
 		usage
