Added support for specifying additional volumes at the sandbox, project and user levels

diff --git a/bin/sb-project b/bin/sb-project
--- a/bin/sb-project
+++ b/bin/sb-project
@@ -112,7 +112,29 @@ EOF
 		echo  "Failed\n$SCRIPT_NAME: Error: Failed to create project file '$project_env_path'"
 		exit 1
 	fi
-  echo "Done"
+
+  project_compose_volumes_path="$path_abs/sb-project-compose-include.yml"
+  echo "$SCRIPT_NAME: Creating file: $project_compose_volumes_path"
+  cat <<EOF > $project_compose_volumes_path
+# Example: Mount an additional dev project into the container
+#
+# services:
+#   sandbox:
+#         volumes:
+#             # Mount another_project/ in the host to /workspace/another_project
+#             - workspace_main:/workspace/user_another_project:delegated    
+# volumes:
+#     user_another_project:
+#         driver: local
+#         driver_opts:
+#             type: none
+#             device: /path/to/another_project
+#             o: bind
+EOF
+  if [ $? -ne 0 ]; then
+		echo  "Failed\n$SCRIPT_NAME: Error: Failed to create project file '$project_compose_volumes_path'"
+		exit 1
+	fi
 
   echo "$SCRIPT_NAME: Creating dir : ${project_modules_dir_path}/"
   mkdir -p $project_modules_dir_path
diff --git a/bin/sb-user b/bin/sb-user
--- a/bin/sb-user
+++ b/bin/sb-user
@@ -84,6 +84,7 @@ init_user_env() {
 
   user_env_path=$user_sb_env_root/user.env
   user_secrets_env_path=$user_sb_env_root/user-secrets.env
+  user_compose_include_path=$user_sb_env_root/user-compose-include.yml
   user_modules_dir_path=$user_sb_env_root/modules
   user_example_module_dir_path=$user_modules_dir_path/user-example
 
@@ -102,10 +103,31 @@ EOF
 
   echo "$SCRIPT_NAME: Creating file: $user_secrets_env_path"
   cat <<EOF > $user_secrets_env_path
-#CLAUDE_CODE_OAUTH_TOKEN=
 EOF
   if [ $? -ne 0 ]; then
 		echo  "$SCRIPT_NAME: Aborting sandbox user config initialization- failed to create file '$user_secrets_env_path'"
+		exit 1
+	fi
+
+  echo "$SCRIPT_NAME: Creating file: $user_compose_include_path"
+  cat <<EOF > $user_compose_include_path
+# Example: Mount an additional dev project into the container
+#
+# services:
+#   sandbox:
+#         volumes:
+#             # Mount another_project/ in the host to /workspace/another_project
+#             - workspace_main:/workspace/user_another_project:delegated    
+# volumes:
+#     user_another_project:
+#         driver: local
+#         driver_opts:
+#             type: none
+#             device: /path/to/another_project
+#             o: bind
+EOF
+  if [ $? -ne 0 ]; then
+		echo  "$SCRIPT_NAME: Aborting sandbox user config initialization- failed to create file '$user_compose_include_path'"
 		exit 1
 	fi
 
